### ISSUE TITLE
datumJsonToCbor throw Unsupported type

### ISSUE THREAD

**Issue by judeebene** [Berry-Pool/lucid#23]
@alessandrokonrad 
Version: 0.2.6

When calling collectFrom function 

datumJsonToCbor throw Unsupported type

it seems datumJsonToCbor might need to check for number type as well just like Data.to functions

I will test more, great Job

**Comment by alessandrokonrad** [comment]
Thanks, I think I fixed the issue already. Came across something before where I got the same error. Try out `0.2.7`, I just released it. Lemme know if that fixes the issue for you.

**Comment by judeebene** [comment]
Hi @alessandrokonrad ,

for some unknown reason i am still having this error in the latest version.
I have checked the datum Json return from `https://cardano-testnet.blockfrost.io/api/v0/scripts/datum/3519db34d615e9b5bd0ee5a3cbe5bb2546bd9d3e2386677136ec0acfde7c34a4` to see if there is any type that is not supported in the functions but i cannot find any.
This is the sample  datum json return used: https://gist.github.com/judeebene/f588674218e088c8a8783022258d178a

passing the sample json to the datumJsonToCbor throw Unsupported type.

**Comment by judeebene** [comment]
@alessandrokonrad confirmed this has been fixed now , testing locally , Thank you
